# Generated by Django 2.1.5 on 2019-06-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
