# Generated by Django 2.1.5 on 2019-07-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190629_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
