# Generated by Django 2.1.5 on 2019-06-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190629_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
