# Generated by Django 2.1.5 on 2019-06-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='round',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
